window.$ = window.jQuery = require("jquery")
require("popper.js")
require("bootstrap")
require("select2")
window.List = require("list.js")
window.swal = require("sweetalert")
window.toastr = require("toastr")
window.NProgress = require("nprogress")
